config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :theatre_movies
  resources :movies
  resources :theatres
  get '/search' => 'movies#search', :as => 'search_movie'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :name, presence: true, uniqueness:true
  has_many :theatres, :through => :theatre_movies
  has_many :theatre_movies, :dependent => :destroy

  def self.search(search)

       where("name LIKE :search OR actorname LIKE :search OR directorname LIKE :search OR language LIKE :search OR showtime LIKE :search", search: "%#{search}%")  
  end

end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :movies, :through => :theatre_movies
  has_many :theatre_movies, :dependent => :destroy
end

app/models/theatre_movie.rb
class TheatreMovie < ApplicationRecord
  validates_uniqueness_of :movie_id, :scope => [:theatre_id]
  belongs_to :theatre
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.search(params[:search])
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].blank?
      redirect_to(movie_path, alert: "Empty Field") and return
    else
      @paramter = params[:search].downcase
      @results = Movie.all.where("name LIKE :search", search: "%#{@paramter}")
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :industry, :actorname, :directorname, :language, :showtime, :search)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/theatre_movies_controller.rb
class TheatreMoviesController < ApplicationController
  before_action :set_theatre_movie, only: [:show, :edit, :update, :destroy]

  # GET /theatre_movies
  # GET /theatre_movies.json
  def index
    @theatre_movies = TheatreMovie.all
  end

  # GET /theatre_movies/1
  # GET /theatre_movies/1.json
  def show
  end

  # GET /theatre_movies/new
  def new
    @theatre_movie = TheatreMovie.new
  end

  # GET /theatre_movies/1/edit
  def edit
  end

  # POST /theatre_movies
  # POST /theatre_movies.json
  def create
    @theatre_movie = TheatreMovie.new(theatre_movie_params)

    respond_to do |format|
      if @theatre_movie.save
        format.html { redirect_to @theatre_movie, notice: 'Theatre movie was successfully created.' }
        format.json { render :show, status: :created, location: @theatre_movie }
      else
        format.html { render :new }
        format.json { render json: @theatre_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theatre_movies/1
  # PATCH/PUT /theatre_movies/1.json
  def update
    respond_to do |format|
      if @theatre_movie.update(theatre_movie_params)
        format.html { redirect_to @theatre_movie, notice: 'Theatre movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @theatre_movie }
      else
        format.html { render :edit }
        format.json { render json: @theatre_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatre_movies/1
  # DELETE /theatre_movies/1.json
  def destroy
    @theatre_movie.destroy
    respond_to do |format|
      format.html { redirect_to theatre_movies_url, notice: 'Theatre movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theatre_movie
      @theatre_movie = TheatreMovie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theatre_movie_params
      params.require(:theatre_movie).permit(:theatre_id, :movie_id)
    end
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  before_action :set_theatre, only: [:show, :edit, :update, :destroy]

  # GET /theatres
  # GET /theatres.json
  def index
    @theatres = Theatre.all
  end

  # GET /theatres/1
  # GET /theatres/1.json
  def show
  end

  # GET /theatres/new
  def new
    @theatre = Theatre.new
  end

  # GET /theatres/1/edit
  def edit
  end

  # POST /theatres
  # POST /theatres.json
  def create
    @theatre = Theatre.new(theatre_params)

    respond_to do |format|
      if @theatre.save
        format.html { redirect_to @theatre, notice: 'Theatre was successfully created.' }
        format.json { render :show, status: :created, location: @theatre }
      else
        format.html { render :new }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theatres/1
  # PATCH/PUT /theatres/1.json
  def update
    respond_to do |format|
      if @theatre.update(theatre_params)
        format.html { redirect_to @theatre, notice: 'Theatre was successfully updated.' }
        format.json { render :show, status: :ok, location: @theatre }
      else
        format.html { render :edit }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatres/1
  # DELETE /theatres/1.json
  def destroy
    @theatre.destroy
    respond_to do |format|
      format.html { redirect_to theatres_url, notice: 'Theatre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theatre
      @theatre = Theatre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theatre_params
      params.require(:theatre).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/theatre_movies_helper.rb
module TheatreMoviesHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.text_field :industry %>
  </div>

  <div class="field">
    <%= form.label :actorname %>
    <%= form.text_field :actorname %>
  </div>

  <div class="field">
    <%= form.label :directorname %>
    <%= form.text_field :directorname %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :showtime %>
    <%= form.datetime_field :showtime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<div class='search-area d-flex justify-content-center'>
   <h5>Search Movies:</h5>
   <%= form_tag movies_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
   <% end %>
 </div>

 <hr>


 <div class="container">
   <div class="card">
    <div class="card-body d-flex justify-content-center">
      <%= link_to "Create New Movie", new_movie_path, class: "btn btn-outline-success" %>
    </div>
   </div>


  <% @movies.each do |movie| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-2">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by Rajashekar Pallala
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to movie.name, movie_path(movie), class: "text-success" %></h5>
            <h5 class="card-title"><%= link_to movie.industry, movie_path(movie), class: "text-success" %></h5>
            <h5 class="card-title"><%= link_to movie.actorname, movie_path(movie), class: "text-success" %></h5>
            <h5 class="card-title"><%= link_to movie.directorname, movie_path(movie), class: "text-success" %></h5
            <h5 class="card-title"><%= link_to movie.language, movie_path(movie), class: "text-success" %></h5>
            <%= link_to "View", movie_path(movie), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_movie_path(movie), class: "btn btn-outline-info" %>
            <%= link_to "Delete", movie_path(movie), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(movie.created_at) %> ago,
            edited <%= time_ago_in_words(movie.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="card">
   <div class="card-body d-flex justify-content-center">
     <%= link_to "Create New Movie", new_movie_path, class: "btn btn-outline-success" %>
   </div>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @movie.industry %>
</p>

<p>
  <strong>Actorname:</strong>
  <%= @movie.actorname %>
</p>

<p>
  <strong>Directorname:</strong>
  <%= @movie.directorname %>
</p>

<p>
  <strong>Language:</strong>
  <%= @movie.language %>
</p>

<p>
  <strong>Showtime:</strong>
  <%= @movie.showtime %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/pages/home.html.erb
<h4>Welocme To Ticket Booking Application</h4>

<div class="container">
  <div class="card">
   <div class="card-body d-flex justify-content-center">
     <%= link_to "Movies Listing Page", movies_path, class: "btn btn-success" %>
   </div>
  </div>

</div>

<footer class="footer1">
<div class="footer-copyright text-center py-3">© 2020 Created By:
  <a href="https://github.com/Rajashekar-P/"> Rajashekar Pallala</a>
</div>

</footer>

app/views/theatre_movies/_form.html.erb
<%= form_with(model: theatre_movie, local: true) do |form| %>
  <% if theatre_movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theatre_movie.errors.count, "error") %> prohibited this theatre_movie from being saved:</h2>

      <ul>
        <% theatre_movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :theatre_id %>
    <%= form.text_field :theatre_id %>
  </div>

  <div class="field">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/theatre_movies/edit.html.erb
<h1>Editing Theatre Movie</h1>

<%= render 'form', theatre_movie: @theatre_movie %>

<%= link_to 'Show', @theatre_movie %> |
<%= link_to 'Back', theatre_movies_path %>

app/views/theatre_movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Theatre Movies</h1>

<table>
  <thead>
    <tr>
      <th>Theatre</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theatre_movies.each do |theatre_movie| %>
      <tr>
        <td><%= theatre_movie.theatre.name %></td>
        <td><%= theatre_movie.movie.name %></td>
        <td><%= link_to 'Show', theatre_movie %></td>
        <td><%= link_to 'Edit', edit_theatre_movie_path(theatre_movie) %></td>
        <td><%= link_to 'Destroy', theatre_movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theatre Movie', new_theatre_movie_path %>

app/views/theatre_movies/new.html.erb
<h1>New Theatre Movie</h1>

<%= render 'form', theatre_movie: @theatre_movie %>

<%= link_to 'Back', theatre_movies_path %>

app/views/theatre_movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Theatre:</strong>
  <%= @theatre_movie.theatre_id %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @theatre_movie.movie_id %>
</p>

<%= link_to 'Edit', edit_theatre_movie_path(@theatre_movie) %> |
<%= link_to 'Back', theatre_movies_path %>

app/views/theatres/_form.html.erb
<%= form_with(model: theatre, local: true) do |form| %>
  <% if theatre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theatre.errors.count, "error") %> prohibited this theatre from being saved:</h2>

      <ul>
        <% theatre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/theatres/edit.html.erb
<h1>Editing Theatre</h1>

<%= render 'form', theatre: @theatre %>

<%= link_to 'Show', @theatre %> |
<%= link_to 'Back', theatres_path %>

app/views/theatres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Theatres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theatres.each do |theatre| %>
      <tr>
        <td><%= theatre.name %></td>
        <td><%= link_to 'Show', theatre %></td>
        <td><%= link_to 'Edit', edit_theatre_path(theatre) %></td>
        <td><%= link_to 'Destroy', theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theatre', new_theatre_path %>

app/views/theatres/new.html.erb
<h1>New Theatre</h1>

<%= render 'form', theatre: @theatre %>

<%= link_to 'Back', theatres_path %>

app/views/theatres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theatre.name %>
</p>

<%= link_to 'Edit', edit_theatre_path(@theatre) %> |
<%= link_to 'Back', theatres_path %>